name: publish blog

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          
      - name: Build
        run: hugo --minify --baseURL https://www.huderlem.com/blog

      - name: Publish Site
        uses: garygrossgarten/github-action-scp@v0.7.1
        with:
          local: public
          remote: /home/public/blog
          host: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          rmRemote: true
